djdb/urls.py
###
### Copyright 2009 The Chicago Independent Radio Project
### All Rights Reserved.
###
### Licensed under the Apache License, Version 2.0 (the "License");
### you may not use this file except in compliance with the License.
### You may obtain a copy of the License at
###
###     http://www.apache.org/licenses/LICENSE-2.0
###
### Unless required by applicable law or agreed to in writing, software
### distributed under the License is distributed on an "AS IS" BASIS,
### WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
### See the License for the specific language governing permissions and
### limitations under the License.
###

"""URLs for the DJ Database."""

from django.conf import settings
from django.conf.urls.defaults import patterns, url
from djdb import models


# "/djdb/" has six characters, and needs to be stripped off when assembling
# our pattern.
IMAGE_URL_PATTERN = '^' + models.DjDbImage.URL_PREFIX[6:]


urlpatterns = patterns(
    '',
    # Landing page
    url(r'^/?$', 'djdb.views.landing_page', name='djdb.landing_page'),

    # Activity page
    (r'activity', 'djdb.views.activity_page'),

    # Reviews page
    (r'reviews', 'djdb.views.reviews_page'),

    # DJ home pgae
    (r'user/?(.*)', 'djdb.views.user_info_page'),

    # Tracks played page.
    ('tracks_played/(.*)', 'djdb.views.tracks_played_page'),

    # Artist information page
    (r'artist/(.*)/info', 'djdb.views.artist_info_page'),

    # Update albums (from landing page or artist info page)
    (r'^update_albums$', 'djdb.views.update_albums'),
    (r'artist/.*/update', 'djdb.views.update_albums'),

    # Un/Revoke an artist.
    (r'artist/(.*)/revoke', 'djdb.views.artist_revoke'),
    (r'artist/(.*)/unrevoke', 'djdb.views.artist_unrevoke'),

    # Artist search for jquery.autocomplete
    (r'artist/search\.txt', 'djdb.views.artist_search_for_autocomplete'),

    # More flexible autocomplete search
    url(r'track/search\.json', 'djdb.views.track_search',
        name='djdb.views.track_search'),

    # Album information page
    (r'album/(.*)/info', 'djdb.views.album_info_page'),

    # Un/Revoke an album.
    (r'album/(.*)/revoke', 'djdb.views.album_revoke'),
    (r'album/(.*)/unrevoke', 'djdb.views.album_unrevoke'),

    # Update tracks.
    (r'album/(.*)/update', 'djdb.views.update_tracks'),

    # Un/Revoke track.
    (r'track/(.*)/revoke', 'djdb.views.track_revoke'),
    (r'track/(.*)/unrevoke', 'djdb.views.track_unrevoke'),

    # Album reviews.
    (r'album/(.*)/new_review', 'djdb.views.album_edit_review'),
    (r'album/(.*)/edit_review/(.*)', 'djdb.views.album_edit_review'),
    (r'album/(.*)/hide_review/(.*)', 'djdb.views.album_hide_unhide_review'),
    (r'album/(.*)/unhide_review/(.*)', 'djdb.views.album_hide_unhide_review'),
    (r'album/(.*)/delete_review/(.*)', 'djdb.views.album_delete_review'),
    (r'album/(.*)/delete_review', 'djdb.views.album_delete_review'),

    # Album comments.
    (r'album/(.*)/new_comment', 'djdb.views.album_edit_comment'),
    (r'album/(.*)/edit_comment/(.*)', 'djdb.views.album_edit_comment'),
    (r'album/(.*)/hide_comment/(.*)', 'djdb.views.album_hide_unhide_comment'),
    (r'album/(.*)/unhide_comment/(.*)', 'djdb.views.album_hide_unhide_comment'),
    (r'album/(.*)/delete_comment/(.*)', 'djdb.views.album_delete_comment'),
    (r'album/(.*)/delete_comment', 'djdb.views.album_delete_comment'),

    # Album tags.
    (r'tags$', 'djdb.views.list_tags'),
    (r'tags/new', 'djdb.views.new_tag'),
    (r'tag/(.*)', 'djdb.views.edit_tag'),
    (r'album/(.*)/add_tag', 'djdb.views.album_add_tag'),
    (r'album/(.*)/remove_tag', 'djdb.views.album_remove_tag'),

    # Album search for jquery.autocomplete
    (r'album/search\.txt', 'djdb.views.album_search_for_autocomplete'),

    # Browse the database.
    (r'browse/(.+)/(.+)', 'djdb.views.browse_page'),
    (r'new_browse', 'djdb.views.new_browse_page'),

    # Album category page.
    (r'category/(.*)', 'djdb.views.category_page'),

    # Track search for jquery.autocomplete
    (r'track/search\.txt', 'djdb.views.track_search_for_autocomplete'),

    # Label search for jquery.autocomplete
    (r'label/search\.txt', 'djdb.views.label_search_for_autocomplete'),

    # Crate.
    (r'^crate/?$', 'djdb.views.crate_page'),
    (r'crate/add_item', 'djdb.views.add_crate_item'),
    (r'crate/remove_item', 'djdb.views.remove_crate_item'),
    (r'crate/reorder', 'djdb.views.reorder_crate_items'),
    (r'crate/send_to_playlist/(.*)', 'djdb.views.send_to_playlist'),
    (r'crate/(.+)/add_item', 'djdb.views.add_crate_item'),
    (r'crate/(.+)/remove_item', 'djdb.views.remove_crate_item'),
    (r'crate/(.+)/reorder', 'djdb.views.reorder_crate_items'),
    (r'^crate/(.*)', 'djdb.views.crate_page'),

    (r'update/artists/bulk_add', 'djdb.views.artists_bulk_add'),

    # Images
    (IMAGE_URL_PATTERN, 'djdb.views.image'),

    # Bootstrap -- development only!
    (r'_bootstrap', 'djdb.bootstrap.bootstrap'),

    (r'_copy_created', 'djdb.views._copy_created'),

    # Web hook for index optimization
    (r'_hooks/optimize_index', 'djdb.hooks.optimize_index'),
)

urls.py
# Copyright 2008 Google Inc.
# Copyright 2009 The Chicago Independent Radio Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
from django.conf import settings
from django.conf.urls.defaults import *

urlpatterns = patterns(
    '',
    # To ensure that each the URL-spaces exposed by applications are
    # unique, URLs should be prefixed with a path component identical
    # to the application's name.  For example: if the DJ Database
    # app lives under the 'djdb' subdirectory, each of
    # that app's URLs should be of the form
    # http://host/djdb/XXXXX.

    # The lone exception to our URL naming convention is the main
    # landing page.
    ('^$', 'landing_page.views.landing_page'),

    # The site authentication system.
    ('^auth/', include('auth.urls')),

    # The DJ database.
    ('^djdb/', include('djdb.urls')),

    # DJ Playlists.
    ('^playlists/', include('playlists.urls')),

    (r'^traffic_log/', include('traffic_log.urls')),

    ('^common/', include('common.urls')),

    ('^jobs/', include('jobs.urls')),

    ('^errors/', include('errors.urls')),

    # Facebook app.
    ('^fbapp/', include('fbapp.urls')),

    (r'^m', 'landing_page.views.go_mobile'),

    ('^_ah/warmup/?', 'common.views.appengine_warmup'),

    # A catch-all rule to generate a 404.
    (r'', 'landing_page.views.four_oh_four'),
)

djdb/forms.py
###
### Copyright 2009 The Chicago Independent Radio Project
### All Rights Reserved.
###
### Licensed under the Apache License, Version 2.0 (the "License");
### you may not use this file except in compliance with the License.
### You may obtain a copy of the License at
###
###     http://www.apache.org/licenses/LICENSE-2.0
###
### Unless required by applicable law or agreed to in writing, software
### distributed under the License is distributed on an "AS IS" BASIS,
### WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
### See the License for the specific language governing permissions and
### limitations under the License.
###

"""Forms for DJ Database."""

from datetime import datetime
from django import forms
from django.utils.translation import ugettext_lazy as _
from djdb import models
from common.autoretry import AutoRetry
from google.appengine.ext import db

ALBUM_CATEGORY_CHOICES = [["", ""]]
ALBUM_CATEGORY_CHOICES += zip(models.ALBUM_CATEGORIES,
                              [category.replace('_', ' ').capitalize() for category in models.ALBUM_CATEGORIES])
PAGE_SIZE_CHOICES = [[10, 10],
                     [25, 25],
                     [50, 50],
                     [100, 100]]
ORDER_CHOICES = [['created', 'created'],
                 ['author', 'author']]
BROWSE_ORDER_CHOICES = [['created', 'created'],
                 ['author', 'author']]
months =['January', 'February', 'March', 'April', 'May', 'June', 'July',
         'August', 'September', 'October', 'November', 'December']
MONTH_CHOICES = zip(range(1, 13), months)
days = range(1, 32)
DAY_CHOICES = zip(days, days)
years = range(2009, datetime.now().year + 1)
YEAR_CHOICES = zip(years, years)

SORT_BY_CHOICES = [['', '-'],
                   ['artist', 'artist'],
                   ['album', 'album'],
                   ['track', 'track'],
                   ['duration', 'duration']]

class PartialAlbumForm(forms.Form):
    pronunciation = forms.CharField(required=False,
                                    widget=forms.TextInput(attrs={'size': 40}))
    label = forms.CharField(required=False,
                            widget=forms.TextInput(attrs={'size': 40}))
    year = forms.IntegerField(required=False,
                              widget=forms.TextInput(attrs={'size': 4, 'maxlength': 4}))
    is_compilation = forms.BooleanField(required=False, label='Is a compilation:')
    is_heavy_rotation = forms.BooleanField(required=False,
                                           label=_("Heavy rotation"))
    is_light_rotation = forms.BooleanField(required=False,
                                           label=_("Light rotation"))
    is_local_classic = forms.BooleanField(required=False,
                                          label=_("Local classic"))
    is_local_current = forms.BooleanField(required=False,
                                          label=_("Local current"))

class PartialArtistForm(forms.Form):
    pronunciation = forms.CharField(required=False,
                                    widget=forms.TextInput(attrs={'size': 40}))

class ListReviewsForm(forms.Form):
    author = forms.CharField(required=False)
    author_key = forms.CharField(required=False, widget=forms.HiddenInput)
#    category = forms.ChoiceField(required=False, choices=ALBUM_CATEGORY_CHOICES)
    page_size = forms.ChoiceField(required=False, choices=PAGE_SIZE_CHOICES)
    order = forms.ChoiceField(required=False, choices=ORDER_CHOICES)

class TagForm(forms.Form):
    name = forms.CharField(required=True)
    description = forms.CharField(widget=forms.Textarea, required=False)

class ListTracksPlayedForm(forms.Form):
    from_month = forms.ChoiceField(required=False, choices=MONTH_CHOICES)
    from_day = forms.ChoiceField(required=False, choices=DAY_CHOICES)
    from_year = forms.ChoiceField(required=False, choices=YEAR_CHOICES)
    page_size = forms.ChoiceField(required=False, choices=PAGE_SIZE_CHOICES)

class ListActivityForm(forms.Form):
    from_month = forms.ChoiceField(required=False, choices=MONTH_CHOICES)
    from_day = forms.ChoiceField(required=False, choices=DAY_CHOICES)
    from_year = forms.ChoiceField(required=False, choices=YEAR_CHOICES)

class CrateForm(forms.Form):
    artist = forms.CharField(required=False,
                             label=_("Artist"))
    track = forms.CharField(required=False,
                            label=_("Song Title"))
    album = forms.CharField(required=False,
                            label=_("Album"))
    label = forms.CharField(required=False,
                            label=_("Label"))
    is_heavy_rotation = forms.BooleanField(required=False,
                                           label=_("Heavy rotation"))
    is_light_rotation = forms.BooleanField(required=False,
                                           label=_("Light rotation"))
    is_local_classic = forms.BooleanField(required=False,
                                          label=_("Local classic"))
    is_local_current = forms.BooleanField(required=False,
                                          label=_("Local current"))
    notes = forms.CharField(required=False,
                            label=_("Song Notes"),
                            widget=forms.Textarea(attrs={'class':'text'}))

class CrateItemsForm(forms.Form):
    crates = forms.ChoiceField(required=True, label=_("Select crate"))
    name = forms.CharField(required=False, label=_("Name"))
    is_default = forms.BooleanField(required=False, label=_("Default crate"))
    sort_by = forms.ChoiceField(required=False, choices=SORT_BY_CHOICES)

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(CrateItemsForm, self).__init__(*args, **kwargs)

        crates_field = []
        crates = AutoRetry(models.Crate.all().filter("user =", user)).fetch(999)
        for crate in crates:
            if crate.name is None or crate.name == '':
                name = "<No name>"
            else:
                name = crate.name
            if crate.is_default:
                name += " (default)"
            crates_field.append((crate.key(), name))
        self.fields['crates'].choices = crates_field

        if 'is_default' in args[0] and args[0]['is_default']:
            self.fields['is_default'].widget.attrs['disabled'] = True

class BrowseForm(forms.Form):
    page_size = forms.ChoiceField(required=False, choices=PAGE_SIZE_CHOICES)
    reviewed = forms.BooleanField(required=False)
    not_reviewed = forms.BooleanField(required=False)
#    order = forms.ChoiceField(required=False)

    def __init__(self, *args, **kwargs):
        entity_kind = kwargs.pop('entity_kind')
        super(BrowseForm, self).__init__(*args, **kwargs)

        choices = [('artist', 'artist')]
        if entity_kind == 'album' or entity_kind == 'track':
            choices.append(('album', 'album'))
        if entity_kind == 'track':
            choices.append(('track', 'track'))
#        self.fields['order'].choices = choices

landing_page/views.py
###
### Copyright 2009 The Chicago Independent Radio Project
### All Rights Reserved.
###
### Licensed under the Apache License, Version 2.0 (the "License");
### you may not use this file except in compliance with the License.
### You may obtain a copy of the License at
###
###     http://www.apache.org/licenses/LICENSE-2.0
###
### Unless required by applicable law or agreed to in writing, software
### distributed under the License is distributed on an "AS IS" BASIS,
### WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
### See the License for the specific language governing permissions and
### limitations under the License.
###

"""Views for the site landing page."""

from django import http
from django.template import RequestContext, loader


mobile_app_urls = {
    'iphone': 'http://itunes.apple.com/us/app/chirp-radio/id373395037?mt=8',
    'android': 'https://market.android.com/details?id=org.chirpradio.mobile',
    'blackberry': 'http://chirpradio.org/phones#19480',
    '__default__': 'http://chirpradio.org/phones'
}


def landing_page(request):
    template = loader.get_template('landing_page/landing_page.html')
    ctx = RequestContext(request, {
            'title': 'Welcome to chirpradio'
            })
    return http.HttpResponse(template.render(ctx))


def four_oh_four(request):
    return http.HttpResponse("No such page: " + request.path,
                             mimetype="text/plain",
                             status=404)


def go_mobile(request):
    ua = request.META.get('HTTP_USER_AGENT', '').lower()
    if 'iphone' in ua:
        url = mobile_app_urls['iphone']
    elif 'android' in ua:
        url = mobile_app_urls['android']
    elif 'blackberry' in ua:
        url = mobile_app_urls['blackberry']
    else:
        url = mobile_app_urls['__default__']
    return http.HttpResponseRedirect(url)

templates/djdb/activity.html
{% extends "djdb/internal_page.html" %}

{% load common_extras %}
{% load djdb_extras %}

{% block breadcrumbs %}
<a href="/">chipradio home</a> /
<a href="/djdb/">DJ Database home</a>
{% endblock %}

{% block content %}

<form action="/djdb/activity" method="post">
  {{ form }}
  <input type="submit" name="search" value="Search"/>
  <br/>
  <input type="submit" name="prev" onclick="document.paging.bookmark.value='{{ prev }}'" value="Previous Page"/>
  <input type="submit" name="next" onclick="document.paging.bookmark.value='{{ next }}'" value="Next Page"/>
  <input type="hidden" name="start_dt" value="{{ start_dt|date:"Y-m-d" }}"/>
</form>

<h3>Activity for {{ start_dt|date:"D F j, Y" }}:</h3>

{% if recent_activity %}
  {% for dt, items in recent_activity %}
{{ dt|date:"D F j, Y P" }}
<ul class="activity">
    {% for type, item in items %}
  <li class="activity_{{ type }}">{{ item|safe }}</li>
    {% endfor %}
</ul>
  {% endfor %}
{% else %}
  No activity.
  <br/><br/>
{% endif %}

<form action="/djdb/activity" method="post">
  <input type="submit" name="prev" onclick="document.paging2.bookmark.value='{{ prev }}'" value="Previous Page"/>
  <input type="submit" name="next" onclick="document.paging2.bookmark.value='{{ next }}'" value="Next Page"/>
  <input type="hidden" name="start_dt" value="{{ start_dt|date:"Y-m-d" }}"/>
</form>

{% endblock %}

templates/djdb/album_edit_comment.html
{% extends "djdb/internal_page.html" %}

{% block breadcrumbs %}
<a href="/">chipradio home</a> /
<a href="/djdb/">DJ Database home</a>
{% endblock %}

{% block content %}

You are
{% if edit %}
editing your comment
{% else %}
writing a new comment
{% endif %}
for
<a href="{{ album.url }}"><b>{{ album.title }}</b></a>
by
<a href="{{ album.artist_url }}">{{ album.artist_name }}</a>.

<p>
Please proofread your comment carefully before you submit it.
</p>

<form action="{{ comment.key }}" method="post">
{% if preview %}
<p>
Your text of your comment will look like this when it is displayed:
</p>
<div style="BACKGROUND-COLOR: #f0f0f0; PADDING: 10px; BORDER: black 3px solid">
<p>
<blockquote>
{{ preview|safe }}
</blockquote>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<small>--posted by
{{ user }}
on {{ chicago_now|date:"F j, Y P" }}</small>
</p>
</div>

<p>
If this looks good to you, click on "Save".  Otherwise you can
continue to edit the post in the form below.
</p>
<input type="submit" name="save" value="Save">
<hr><br><br>
{% endif %}

<p>
You can use basic HTML markup in the body of your comment; unsupported
HTML will be stripped out automatically.
</p>
<p>
The allowed HTML tags are: {{ valid_html_tags }}
</p>
<table>
  {{ form.as_table }}
</table>
<input type="submit" name="preview" value="Preview">

{% endblock %}

templates/djdb/album_edit_review.html
{% extends "djdb/internal_page.html" %}

{% block breadcrumbs %}
<a href="/">chipradio home</a> /
<a href="/djdb/">DJ Database home</a>
{% endblock %}

{% block content %}

{% block extrahead %}
<script type="text/javascript" 
    src="/media/common/js/jquery/jquery-1.3.1.js"></script>
<script type="text/javascript" 
    src="/media/common/js/jquery-autocomplete/jquery.autocomplete.js"></script>
<script type="text/javascript" src="/media/djdb/js/djdb_user.js"></script>
{% endblock %}

You are
{% if edit %}
editing the
{% else %}
writing a new
{% endif %}
review of
<a href="{{ album.url }}"><b>{{ album.title }}</b></a>
by
<a href="{{ album.artist_url }}">{{ album.artist_name }}</a>.

<p>
Please proofread your review carefully before you submit it.
</p>

<form action="{{ review.key }}" method="post">
{% if preview %}
    <p>
The text of your review will look like this when it is displayed:
    </p>
    <div style="BACKGROUND-COLOR: #f0f0f0; PADDING: 10px; BORDER: black 3px solid">
        <b>{{ album.artist_name }} / {{ album }} / {{ label }} / {{ year }}</b>

        <p>
            <blockquote>
{{ preview|safe }}
            </blockquote>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<small>--posted by
{{ author_name }}
on {{ chicago_now|date:"F j, Y P" }}</small>
        </p>
    </div>
    <p>
If this looks good to you, click on "Save".  Otherwise you can
continue to edit the post in the form below.
    </p>
    <input type="submit" name="save" value="Save"/>
    <hr/><br/><br/>
{% endif %}
    <p>
You can use basic HTML markup in the body of your review; unsupported
HTML will be stripped out automatically.
    </p>
    <p>
The allowed HTML tags are: {{ valid_html_tags }}
    </p>
    <table>
  {{ form.as_table }}
    </table>
    <input id="id_author_key" type="hidden" name="author_key" value="{{ author_key }}"/>
    <input type="submit" name="preview" value="Preview">
</form>

{% endblock %}

templates/djdb/album_page.html
{% extends "common/base.html" %}

{% block content %}

<p>
This is the album information page for <b>{{ album.title }}</b> by
<a href="{{ album.artist_url }}">{{ album.artist_name }}</a>.
It is still very primitive.
</p>

<table>
{% for track in album.sorted_tracks %}
<tr>
<td>{{ track.track_num }}.</td>
<td>{{ track.title }}</td>
<td>{{ track.duration }}</td>
<td><small>{{ track.bit_rate_kbps }} kbps</small></td>
</tr>
{% endfor %}
</table>


{% endblock %}

templates/djdb/artist_info_page.html
{% extends "djdb/internal_page.html" %}

{% load common_extras %}
{% load djdb_extras %}

{% block breadcrumbs %}
<a href="/">chipradio home</a> /
<a href="/djdb/">DJ Database home</a>
{% endblock %}

{% block content %}

{% block extrahead %}
<script type="text/javascript" 
    src="/media/common/js/jquery/jquery-1.3.1.js"></script>
<script type="text/javascript" 
    src="/media/djdb/js/djdb.js"></script>
<script type="text/javascript"
    src="/media/djdb/js/djdb_edit_artist.js"></script>
{% endblock %}

{% if artist.pronunciation %}
<i>Pronunciation: {{ artist.pronunciation }}</i>
{% endif %}

{% if msg %}
<div class="success">
{{ msg }}
</div>
{% endif %}

{% if user.is_music_director %}
<div class="edit_artist" style="display: none">
  <form action="" method="post">
    <table>
{{ artist_form.as_table }}
    </table>
    <input type="submit" name="update_artist" value="Update Artist">
    <input class="edit_artist" type="submit" name="cancel" value="Cancel">
  </form>
</div>
{% endif %}

<h3>Albums</h3>

{% if user.is_music_director or user.is_reviewer %}
<form method="post" name="djdbForm" action="update">
  <p>
    Select:
    <a id="select_all" href="">All</a>,
    <a id="select_none" href="">None</a>,
  {% for category in categories %}
    {% if not forloop.first %}, {% endif %}
    <a id="select_{{ category }}" href="">{{ category|replace:"/_/ "|capfirst }}</a>
  {% endfor %}<br/>
Mark/Unmark selected as:
  {% for category in categories %}
    {% if not forloop.first %}, {% endif %}
    <a id="mark_{{ category }}" href="update">{{ category|replace:"/_/ "|capfirst }}</a>
  {% endfor %}
  </p>

  <input type="hidden" name="mark_as"/>
  <input type="hidden" name="response_page" value="artist"/>
  <input type="hidden" name="artist_name" value="{{ artist.name }}"/>
  <input type="hidden" name="show_revoked" value="{{ show_revoked }}"/>
{% endif %}

{% if user.is_music_director %}
  {% if revoked_items %}
    {% if show_revoked %}
<a href="{{ artist.url }}?show_revoked=False">Hide revoked albums.</a>
    {% else %}
<a href="{{ artist.url }}?show_revoked=True">Show revoked albums.</a>
    {% endif %}
  {% endif %}
{% endif %}

<table>
{% for album in albums %}
  {% if not album.revoked or show_revoked %}
    {% if album.revoked %}
  <tr class="revoked">
    {% else %}
  <tr>
    {% endif %}
    {% if user.is_music_director or user.is_reviewer %}
    <td>
      <input type="checkbox" class="checkbox 
    {% for tag in album.current_tags %}
      {% if tag in categories %}
        {{ tag }}
      {% endif %}
    {% endfor %}"
             name="checkbox_{{ forloop.counter }}"/>
      <input type="hidden" name="album_key_{{ forloop.counter }}" value="{{ album.key }}"/>
    </td>
    {% endif %}
    <td>
    {% for tag in album.current_tags %}
      {% if tag in categories %}
      <div class="track_{{ tag }}">{{ tag|replace:"/_/ "|capfirst }}</div>
      {% endif %}
    {% endfor %}
    </td>
    <td><a href="{{ album.url }}">{{ album }}</a></td>
    <td>
    {% ifnotequal album.label None %}
      {{ album.label }}
    {% endifnotequal %}
    </td>
    <td>
    {% ifnotequal album.year None %}
      {{ album.year }}
    {% endifnotequal %}
    </td>
    <td>
      {{ album.num_tracks }} track{{ album.num_tracks|pluralize }}
    </td>
    <td>
    {% if album.num_reviews %}
    {{ album.num_reviews }} review{{ album.num_reviews|pluralize }}
    {% endif %}
    </td>
    <td>
    {% ifincrate user album %}
      <a href="/djdb/crate/remove_item?response_page=artist&user_key={{ user.key }}&item_key={{ album.key }}&show_revoked={{ show_revoked }}"><img src="/media/common/img/remove.png" alt="Remove Album from Crate" title="Remove from Crate"/></a>
    {% else %}
      <a href="/djdb/crate/add_item?response_page=artist&user_key={{ user.key }}&item_key={{ album.key }}&show_revoked={{ show_revoked }}"><img src="/media/common/img/add.png" alt="Add Album to Crate" title="Add to Crate"/></a>
    {% endifincrate %}
    </td>
    {% if user.is_music_director %}
    <td>
      {% if not artist.revoked %}
        {% if album.revoked %}
      <a href="/djdb/album/{{ album.album_id }}/unrevoke?response_page=artist&show_revoked={{ show_revoked }}" title="Unrevoke album"> <img src="/media/common/img/unrevoke_icon.png" alt="Unrevoke album"/></a>
        {% else %}
      <a href="/djdb/album/{{ album.album_id }}/revoke?response_page=artist&show_revoked={{ show_revoked }}" title="Revoke album"> <img src="/media/common/img/revoke_icon.png" alt="Revoke album"/></a>
        {% endif %}
      {% endif %}
    </td>
    {% endif %}
  </tr>
  {% endif %}
{% endfor %}
</table>
{% if user.is_music_director %}
</form>
{% endif %}

{% endblock %}

templates/djdb/tags.html
{% extends "djdb/internal_page.html" %}

{% load common_extras %}
{% load djdb_extras %}

{% block breadcrumbs %}
<a href="/">chipradio home</a> /
<a href="/djdb/">DJ Database home</a>
{% endblock %}

{% block content %}
  
<a href="/djdb/tags/new">Add a New Tag</a>

<table border="1">
  <tr>
    <th>Tag</th>
    <th>Description</th>
  </tr>
  {% if tags %}
    {% for tag in tags %}
  <tr>
    <td><a href="/djdb/tag/{{ tag.name }}">{{ tag.name }}</a></td>
    <td>{% if tag.description %}{{ tag.description }}{% endif %}</td>
  </tr>
    {% endfor %}
  {% else %}
  <tr>
    <td colspan="2">No tags.</td>
  </tr>
  {% endif %}

{% endblock %}